# Generated by Django 4.2.23 on 2025-07-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('photo', models.ImageField(blank=True, upload_to='ideas/%Y%m%d')),
                ('content', models.TextField()),
                ('interest', models.CharField(max_length=32)),
                ('devtool', models.CharField(max_length=32)),
            ],
        ),
    ]
