# Generated by Django 4.2.23 on 2025-07-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='이름')),
                ('kind', models.CharField(max_length=32, verbose_name='종류')),
                ('content', models.TextField(verbose_name='내용')),
            ],
        ),
    ]
