# Generated by Django 4.2.23 on 2025-07-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=32)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('running_time', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('director', models.CharField(max_length=32)),
                ('actors', models.CharField(max_length=200)),
            ],
        ),
    ]
